import pandas as pd
from datetime import datetime

def main():
    # Load the CSV generated by extract_all
    input_file = "data/extracted_data.csv"
    df = pd.read_csv(input_file)

    # Convert 'birthdate' column to datetime
    df['birthdate'] = pd.to_datetime(df['birthdate'])

    # Calculate account age in years and filter rows with accounts < 3 years old
    today = pd.to_datetime("today")
    df['account_age_years'] = (today - df['birthdate']).dt.days / 365
    filtered_df = df[df['account_age_years'] < 3]

    # Save the filtered CSV
    output_file = "data/filtered_accounts.csv"
    filtered_df.to_csv(output_file, index=False)

    print(f"Filtered file saved as: {output_file}")

if __name__ == "__main__":
    main()

